WIP: First draft of a post about the tech stack
SeaGL/seagl.github.io pull request #216
Opened 2020-10-26 13:06 UTC by funnelfiasco

This post is functional but lacks any...heart? I figured I'd throw it open to suggestion from the team, since I can't make any more progress on it myself.

2020-11-06 16:35 UTC, funnelfiasco commented
Anyone want to weigh in on this? It would be nice to get this post out.

2020-11-06 19:01 UTC, eximious commented
Hi Ben,
I think the easiest would be a quick call. I have a few concrete
suggestions and then I think we could get this out.
My number is 617-905-2706 or send me a video link, if you'd rather.
Best,
Deb

On Fri, Nov 6, 2020 at 11:35 AM Ben Cotton <notifications@github.com> wrote:

> Anyone want to weigh in on this? It would be nice to get this post out.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/SeaGL/seagl.github.io/pull/216#issuecomment-723176006>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAE7EIKFCRYH3NVKHLA3KGTSOQQV7ANCNFSM4S7LHTIA>
> .
>

2020-11-06 19:52 UTC, funnelfiasco commented
Updated with awesome suggestions from the awesome @eximious.

@altsalt do I remember you saying there were a few technical changes that needed to be made?

2020-11-06 23:58 UTC, altsalt commented
Working on tech stuff tonight, I suspect to have an answer before tomorrow, otherwise, tomorrow!

2020-11-08 06:46 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +When thinking about what it meant to move SeaGL online, we had to consider how we could preserve that authentic SeaGL experience.
maybe s/SeaGL experience/SeaGL feel/ ?

2020-11-08 06:47 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +When thinking about what it meant to move SeaGL online, we had to consider how we could preserve that authentic SeaGL experience.
just for the second one that is

2020-11-08 06:48 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +While there are some proprietary offerings that provide a glossy user experience, in the end we decided to stick to our core principles.
...that would have provided a glossy...

2020-11-08 06:49 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +This means there is no registration required.
As always, the conference is free to attend and registration is not required.

2020-11-08 06:51 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +We've developed a web-based interface that combines the video streams and the chat channels.
To that end, we've developed...

2020-11-08 06:52 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +Each talk track will have a separate channel, plus additional channels for general chat.
...separate channel/room, alongside a number of additional channels for general chat, announcements, etc.

2020-11-08 06:54 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +In order to recreate the "hallway track" feel, we have a bot that can create breakout rooms on demand.
...we have developed a bot that creates visible "breakout rooms" on demand.

2020-11-08 06:56 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +From there, it's easy to find the conversations that match your interests.
your interests, or stake out a spot for folk to match yours.

2020-11-08 06:57 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +If you want to use your IRC client of choice, you'll be able to do that—all of the text communication will take place on Freenode IRC.
...on the freenode IRC network.

2020-11-08 07:00 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +We'll be publishing documentation soon for anyone who wants to replicate the experience for their own conference.
Furthermore, we'll be spending some time after the event to polish up and document the system for anyone who...

2020-11-08 07:02 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +We'll be publishing documentation soon for anyone who wants to replicate the experience for their own conference.
This line and the one before feel like they belong together, with an additional point about using free software and pre-existing projects, standing on the shoulders of giants, but also giving back for future generations inbetween. Something like that, and but it may not go right here.

2020-11-08 07:03 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +Not-invented-here is a feature in FOSS.
Italicize?

2020-11-08 07:03 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +The chat runs on the [Freenode](http://freenode.net/) IRC network.
I think freenode is lowercased, also add https wherever possible.

2020-11-08 07:12 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +The chat runs on the [Freenode](http://freenode.net/) IRC network.
also, instead of two sentences, maybe something like:
...SeaGL portal, which connects to the [freenode]...

2020-11-08 07:15 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +The presentations and video chats will use the popular [Jitsi](https://jitsi.org/) web conference platform.
Presenters will connect to a [BigBlueButton](https://bigbluebutton.org/) instance graciously provided to us by the [FSF](https://www.fsf.org/).
Their video will be broadcast to a variety of third party streaming sites, as well as being sent to Azure for [live transcription](https://docs.microsoft.com/en-us/azure/media-services/latest/live-transcription) for display within our embedded chat.
Additionally, to further mirror the "hallway track", attendees will be able to open up embedded [Jitsi](https://jitsi.org/) video conferencing rooms on-the-fly inside any of the breakout rooms.

2020-11-08 07:15 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +Because accessibility is important to us, we will have live captioning on the videos.
Strike both of these lines as their info is included in the comment above.

2020-11-08 07:17 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +The main thing we wrote is the seagl-bot.
The orchestration between all of these components is helped along by seagl-bot.

2020-11-08 07:18 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +seagl-bot is an IRC bot designed to help ease the IRC experience.
...experience and make it feel more like a conference.

2020-11-08 07:20 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +In particular, we'd like to thank Andrew, Tree, Keith, sntxrr, and Salt for their work on putting this all together.
...like to extend our thanks to Andrew...

Also, we should verify whether it is Don or sntxrr... who doesn't seem to be part of the SeaGL GH org v_v

Any thoughts on best ordering of names?

2020-11-08 07:22 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +The rest of the organizing committee helped with testing and making the final decision.
As well as the rest of the organizing committee who helped with testing and making the final decision go with the in-house design.

2020-11-08 07:24 UTC, altsalt requested changes
Thanks for putting this all together, I added a number of suggestions. Don't think it will need further approval after, but feel free to ping me!

2020-11-08 07:24 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +Please invite your friends from near and far to hang out with us.
exclamation points !!!

2020-11-08 14:02 UTC, funnelfiasco commented on _posts/2021-01-01-seagl-tech-stack.md
> +In particular, we'd like to thank Andrew, Tree, Keith, sntxrr, and Salt for their work on putting this all together.
Dontxrr provided early comments via email and didn't say anything about his name, so I guess he's fine with it?

I don't remember where the ordering in the names came from. Maybe in order of appearance in the etherpad? Or who's name was said first in the Outreach meeting when we discussed it? In any case, I ascribed no meaning to the ordering, so if anyone has suggestions for ordering, I'm all ears.

2020-11-08 14:14 UTC, funnelfiasco commented
Comments and suggestions incorporated. I'll let this sit for a few hours and merge it tonight with an updated date for Monday publication.

2020-11-08 20:19 UTC, altsalt commented on _posts/2021-01-01-seagl-tech-stack.md
> +In particular, we'd like to thank Andrew, Tree, Keith, sntxrr, and Salt for their work on putting this all together.
@sntxrr confirmation?

@funnelfiasco let's just go alphabetic.

Thanks!

2020-11-08 20:21 UTC, sntxrr commented on _posts/2021-01-01-seagl-tech-stack.md
> +In particular, we'd like to thank Andrew, Tree, Keith, sntxrr, and Salt for their work on putting this all together.
I'm fine with either way.  You can do `@sntxrr/Don` if its easier.

2020-11-08 20:21 UTC, sntxrr commented on _posts/2021-01-01-seagl-tech-stack.md
> +In particular, we'd like to thank Andrew, Tree, Keith, sntxrr, and Salt for their work on putting this all together.
actually, looking at it is now, just do with Don, since we're using real first names.

2020-11-08 20:24 UTC, sntxrr approved these changes

2020-11-09 02:02 UTC, merged