Draft of a post on the decision to go virtual in 2021
SeaGL/seagl.github.io pull request #245
Opened 2021-05-11 17:56 UTC by funnelfiasco

Fixes SeaGL/organization#56

2021-05-18 00:36 UTC, rachelkelly commented on _posts/2021-05-20-format-2021.md
> +Seagulls are not particularly known for clairvoyance, and we did't feel as though we could predict what the pandemic situation will look like in early November.
spelling s/did't/didn't

2021-05-18 00:37 UTC, rachelkelly commented on _posts/2021-05-20-format-2021.md
> +Join us on *the Internet*, Friday, November 5 and Saturday, November 6, 2021!
:)

2021-05-18 00:38 UTC, rachelkelly commented on _posts/2021-05-20-format-2021.md
> +We will be announcing the Call for Participation soon.
we tend to use the phrasing "call for proposas."  do we want to change it to the more inclusive sounding "call for participation"?  I kinda like it but we should be consistent regardless

2021-05-18 00:39 UTC, rachelkelly requested changes
one lil typo to fix, one consideration

2021-05-20 16:06 UTC, altsalt commented on _posts/2021-05-20-format-2021.md
> +We will be announcing the Call for Participation soon.
I like that!

2021-05-20 16:53 UTC, funnelfiasco commented on _posts/2021-05-20-format-2021.md
> +Seagulls are not particularly known for clairvoyance, and we did't feel as though we could predict what the pandemic situation will look like in early November.
Fixed

2021-05-20 16:55 UTC, funnelfiasco commented on _posts/2021-05-20-format-2021.md
> +We will be announcing the Call for Participation soon.
I don't think I did this intentionally, but I like it. If we're agreed to use that phrasing everywhere, then I'll leave it.

2021-06-08 19:46 UTC, merged

2021-06-08 19:46 UTC, funnelfiasco commented
Updated the date and ready to publish

2021-06-08 20:31 UTC, AndrewKvalheim commented
> force-pushed the master branch from f15bc2a to 845f354

I think we lost 3e903e6 through f15bc2a.

![Screenshot from 2021-06-08 13-27-48](https://user-images.githubusercontent.com/1844746/121253187-aa52d100-c85d-11eb-9d69-1e1a22278efe.png)

2021-06-08 20:34 UTC, funnelfiasco commented
WTFrenchfry? Okay, I'll re-add that file

2021-06-08 20:37 UTC, funnelfiasco commented
Ah hell, looks like a bunch of commits got lost from master. Why did it do that, I only did a `--force-with-lease` on the branch I was writing the post in??? @AndrewKvalheim can you force push your copy to overwrite my tragic error and then I'll re-add my post