do not merge: cfp first pass - first new actual cfp blog post in like four years at least?  woo
SeaGL/seagl.github.io pull request #249
Opened 2021-06-12 23:53 UTC by rachelkelly

2021-06-14 01:49 UTC, nhandler requested changes
Thanks for taking a pass at re-writing this blog post. I know you are still working on it, but here are a few initial comments.

2021-06-14 01:49 UTC, nhandler commented on _posts/2021-06-12-cfp.md
> +SeaGL pioneered the idea of CFP Office Hours, and we continue to hold them each year while the Call is open.  Please join us on IRC (link TODO) every week at (time TODO).  You can get advice on your
We should discuss this. I think the feeling last year was that while office hours are a good idea, we should possibly re-think the frequency/forum office hours, as we had very little participation.

2021-06-23 02:52 UTC, nhandler commented on _posts/2021-06-24-cfp.md
> +We are not looking for sponsored talks, however we'd love to welcome you over at our [Sponsorship Prospectus](https://seagl.org/sponsors/2021.html) and give you an opportunity to reach our attendees
We should use `{{ site.custom.url.prospectus }}`

2021-06-23 02:54 UTC, nhandler commented on _posts/2021-06-24-cfp.md
> +When you have submitted, you will be taken to a page called Proposals for SeaGL 2021, and you will see your own talk(s) listed there.  This is where you will add your bio and the talk label ("track")
```suggestion
When you have submitted, you will be taken to a page called Proposals for SeaGL 2021, and you will see your own talk(s) listed there.  This is where you will add your bio and the talk label ("track").  Please note, you will not receive an email confirming your proposed submition.
```

2021-06-23 02:55 UTC, nhandler commented on _posts/2021-06-24-cfp.md
> +SeaGL is a very special conference.  We're a community-focused Free/Libre Open Source Software annual event in Seattle, and since last year, all over the world!  We're looking for technical talks fro
```suggestion
SeaGL is a very special conference.  We're a community-focused Free/Libre Open Source Software annual event in Seattle, and since last year, all over the world virtually!  We're looking for technical talks from folks who usually give community talks, and activism talks from folks who usually give coding deep dives, and so forth. We would love to see you out of your comfort zone.  The categories we used last year were, loosely: Security, Community, Career Development, Tech Culture, Tools, Virtual Life & Work, DevOps, Performance Art! and Miscellaneous, and we had amazing submissions as a result, like Devops Standup and several talks on labor organizing!  We're an independent bunch but we still like to take care of each other.
```

2021-06-23 14:13 UTC, funnelfiasco requested changes
Looks great overall. Just a few minor corrections and open questions.

2021-06-23 14:13 UTC, funnelfiasco commented on _config.yml
> +        prospectus:         /sponsors/SeaGL_Exhibitor_Sponsor_Prospectus_2021.pdf
This file doesn't exist yet.

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +title: 'SeaGL 2021 Call For Proposals'
Did we want to use the "Call for Participation" language that I accidentally used in....something else?

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +Welcome to the 2021 SeaGL Call For Proposals!  Every year, we want to hear from YOU, and we're always looking for speakers who are traditionally underrepresented in tech, and people with perspectives
Minor style nit: I feel like I generally see it styled "CfP", not "CFP". We're internally consistent in this post, but I think we've used "CfP" in some places (like in the website ads that are on their way to Linux Magazine)

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +https://seagl.org/code_of_practice.html
Does this newline break the formatting?

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +These are more than words, they are a framework that we have used and will use in the future when the situation calls for it.  We encourage you to become familiar with the contents of the [SeaGL Code
Is this intended to be a new paragraph? (It seems like it, and I'd argue it should be). If so, it will need a blank line between it and the previous.

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +The [SeaGL Code of Conduct](http://seagl.org/code_of_conduct.html) applies to all staff, all volunteers, all speakers and keynotes, all attendees and viewers, and all sponsors.  SeaGL is dedicated to
It might be good to italicize or bold the sentence "SeaGL is dedicated to providing a harassment-free conference experience for everyone; regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, nationality, race, or religion." so that it stands out.

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +We encourage almost any topic related to open source that you have a personal engagement with. We have created a list of topic tags you might choose to tag your proposal with — these might give you s
s/topic tags/topic/ ? The multiple "tags" close by feels a little clunky.

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +We are not looking for sponsored talks, however we'd love to welcome you over at our [Sponsorship Prospectus](https://seagl.org/sponsors/2021.html) and give you an opportunity to reach our attendees
+1

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +We do not have longer time slots available at SeaGL 2020 because the online medium will make it more critical to present yourself concisely. Please do not propose talks that cannot be presented well
s/2020/2021/

2021-06-23 14:13 UTC, funnelfiasco commented on _posts/2021-06-24-cfp.md
> +We do not have longer time slots available at SeaGL 2020 because the online medium will make it more critical to present yourself concisely. Please do not propose talks that cannot be presented well
Also s/will make/makes/ IMO

2021-06-24 06:49 UTC, rachelkelly commented on _posts/2021-06-24-cfp.md
> +title: 'SeaGL 2021 Call For Proposals'
Eheheheheh...... aw gee.  I think not, we've been consistent over the years with calling it this.  Can we change it elsewhere?  Call for participation could be nice but I think the ship has sailed for this year.

2021-06-24 06:51 UTC, rachelkelly commented on _config.yml
> +        prospectus:         /sponsors/SeaGL_Exhibitor_Sponsor_Prospectus_2021.pdf
Just changed it to the generic sponsor URL page for now, good callout

2021-06-24 18:20 UTC, merged