Add 2022 Keynote Nomination Post
SeaGL/seagl.github.io pull request #325
Opened 2022-04-06 01:12 UTC by nhandler

This change adds a new blog post announcing the 2022 Keynote
Nominations.

2022-04-06 01:24 UTC, funnelfiasco requested changes

2022-04-06 01:24 UTC, funnelfiasco commented on _posts/2022-04-05-keynote-nomination.md
> +While you are welcome to self-nominate yourself, we encourage you to take some time to think about other people you have seen present in the past who you think have an important message to share and
"self-nominate yourself" may be slightly redundant. :-)

2022-04-06 01:24 UTC, funnelfiasco commented on _posts/2022-04-05-keynote-nomination.md
> +One of the things that makes SeaGL unique from other conferences is that we allow the public to play a role in our keynote selection process. For the next two weeks, we will be accepting nominations
"we allow the public to play a role" sounds a little...IDK. Words. Maybe instead something like "our community helps us select our keynote speakers." Focus more on participation and not permission, if that makes sense.

2022-04-06 01:24 UTC, funnelfiasco commented on _posts/2022-04-05-keynote-nomination.md
> +SeaGL will take place virtually November 4-5, 2022.
We are discussing the format as I type this.

2022-04-06 01:24 UTC, funnelfiasco commented on _posts/2022-04-05-keynote-nomination.md
> +Nominees need not have prior keynote experience; we are interested in both new and veteran keynote presenters. If they have been doing exciting work in the Open Source community and have and exciting
I know we don't have a conference theme yet, but is there a theme or a...general sort of thing we'd like to publicly say we're focusing on. ("No" is a fine answer, but if we do, we should call it out)

2022-04-06 02:53 UTC, altsalt commented on _posts/2022-04-05-keynote-nomination.md
> +Nominees need not have prior keynote experience; we are interested in both new and veteran keynote presenters. If they have been doing exciting work in the Open Source community and have and exciting
Yeah ten... but nothing has quite felt right yet.

2022-04-15 01:36 UTC, nhandler commented on _posts/2022-04-05-keynote-nomination.md
> +While you are welcome to self-nominate yourself, we encourage you to take some time to think about other people you have seen present in the past who you think have an important message to share and
```suggestion
While you are welcome to nominate yourself, we encourage you to take some time to think about other people you have seen present in the past who you think have an important message to share and nominate them as well.
```

2022-04-15 01:36 UTC, nhandler commented on _posts/2022-04-05-keynote-nomination.md
> +To nominate someone, please use our [keynote speaker nomination form](https://docs.google.com/forms/d/e/1FAIpQLSfvBo7SX6ku6vmLLvtzbJ_c80b_WfvhUl-GAXpc6nssXCvg-w/viewform?usp=sf_link). You can submit
```suggestion
To nominate someone, please use our [keynote speaker nomination form](https://docs.google.com/forms/d/e/1FAIpQLSfvBo7SX6ku6vmLLvtzbJ_c80b_WfvhUl-GAXpc6nssXCvg-w/viewform?usp=sf_link). You can submit as many nominations as you want (the more the merrier!), and all submissions are completely anonymous. **The form will be open until Friday, April 28 at 11:59pm PDT.**
```

2022-04-15 01:36 UTC, nhandler commented on _posts/2022-04-05-keynote-nomination.md
> +SeaGL will take place virtually November 4-5, 2022.
```suggestion
SeaGL will take place November 4-5, 2022.
```

2022-04-15 22:14 UTC, merged

2022-04-15 22:32 UTC, funnelfiasco commented
Shared on Facebook, Twitter, Mastodon, and LinkedIn. I'll share on Twitter/Mastodon several more times and then on all four again on the 28th